### ISSUE TITLE
How about the performance

### ISSUE THREAD

**Issue by sohaha** [curzodo/plugo#6]
I seem to remember a community project that uses Go to implement a php cli pool, which is somewhat similar to this.

**Comment by curzodo** [comment]
I completely avoided using serialization/de-serialization libraries that tend to encode only structs and not specific values. I would like to test the difference between using a serialization library and what I have written. A while ago I tried measuring the latency of a remote function call by passing the current time in nanoseconds in one plugo to the remote function of another plugo which would then call the current time in nanoseconds again. The same time was always printed out, so the latency for basic functions is at most 100ns.

**Comment by sohaha** [comment]
Looking forward to the follow-up development. 💪🏻
