### ISSUE TITLE
discover exposed functions

### ISSUE THREAD

**Issue by amlwwalker** [curzodo/plugo#9]
Hi
This is cool and I like to see from the example it clearly works on windows (i assume OSX and linux are fine too...?)

I want to create a plugin structure where plugos are required to supply certain functions and if not then error/don't load them. 

Using plugo, is there a way I can either check for the existence from the parent, of functions exposed on a child at runtime, or get a plugo to adhere to an interface?

Thanks

**Comment by curzodo** [comment]
I will add two functions to the library to help you achieve this functionality, as I do believe it is important: CheckFunction, a function that allows you to check if a function with a given Id is exposed on a plugo with a given Id, and Disconnect, a function that allows you to disconnect from a plugo with a given Id.

**Comment by curzodo** [comment]
Hey! I just released a new update that addresses this problem.j

StartChildren() now returns a map. Inside this map is each connected plugo, as well as an array of all the functions it exposes. I have also made public a function Disconnect() which takes a plugo Id as an argument. To implement the functionality you're looking for, you just need to iterate through the map returned by StartChildren(), and check the function list for each plugo for the particular functions you deem necessary, and if any plugo does not expose the functions you're looking for, you can disconnect them.
